channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - pip
  - librosa
  - seaborn
  - altair
  - pip:
    - pyensae
    - qgrid

